RemoveUnusedMethodsInControllersCheck: {
  except_methods: [],
  ignored_files: [
    "app/controllers/static_pages_controller.rb",
    "app/controllers/users_controller.rb",
    "app/controllers/sessions_controller.rb",
    "app/controllers/account_activations_controller.rb"
  ]
}
